http:
  middlewares:
    compress:
      compress: {}
    admin-strip-prefix:
      stripPrefix:
        prefixes:
          - /admin
    lsp-strip-prefix:
      stripPrefix:
        prefixes:
          - /lsp
    pma-strip-prefix:
      stripPrefix:
        prefixes:
          - /pma
