http:
  middlewares:
    compress:
      compress: {}
    oj-trailing-slash:
      redirectRegex:
        regex: "^(https?://[^/]+/oj)$"
        replacement: "${1}/"
        permanent: true
    admin-strip-prefix:
      stripPrefix:
        prefixes:
          - /admin
    lsp-strip-prefix:
      stripPrefix:
        prefixes:
          - /lsp
    pma-strip-prefix:
      stripPrefix:
        prefixes:
          - /pma
