#!/usr/bin/env bash
set -euo pipefail

CONF_PATH="${CONF:?CONF is required}"
mkdir -p "$(dirname "$CONF_PATH")"

cat > "$CONF_PATH" <<JUDGE_CONF
OJ_HOST_NAME=${OJ_HOST_NAME:?OJ_HOST_NAME is required}
OJ_USER_NAME=${OJ_USER_NAME:?OJ_USER_NAME is required}
OJ_PASSWORD=${OJ_PASSWORD:?OJ_PASSWORD is required}
OJ_DB_NAME=${OJ_DB_NAME:?OJ_DB_NAME is required}
OJ_PORT_NUMBER=${OJ_PORT_NUMBER:?OJ_PORT_NUMBER is required}
OJ_RUNNING=${OJ_RUNNING:?OJ_RUNNING is required}
OJ_SLEEP_TIME=${OJ_SLEEP_TIME:?OJ_SLEEP_TIME is required}
OJ_JAVA_TIME_BONUS=${OJ_JAVA_TIME_BONUS:?OJ_JAVA_TIME_BONUS is required}
OJ_JAVA_MEMORY_BONUS=${OJ_JAVA_MEMORY_BONUS:?OJ_JAVA_MEMORY_BONUS is required}
OJ_JAVA_XMS=${OJ_JAVA_XMS:?OJ_JAVA_XMS is required}
OJ_JAVA_XMX=${OJ_JAVA_XMX:?OJ_JAVA_XMX is required}
OJ_SIM_ENABLE=${OJ_SIM_ENABLE:?OJ_SIM_ENABLE is required}
OJ_OI_MODE=${OJ_OI_MODE:?OJ_OI_MODE is required}
OJ_SHM_RUN=${OJ_SHM_RUN:?OJ_SHM_RUN is required}
OJ_USE_MAX_TIME=${OJ_USE_MAX_TIME:?OJ_USE_MAX_TIME is required}
OJ_LANG_SET=${OJ_LANG_SET:?OJ_LANG_SET is required}
JUDGE_CONF

chmod 600 "$CONF_PATH"
echo "Generated $CONF_PATH"
